name: studfood
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.3 <4.0.0"

dependencies:
    cloud_firestore: ^5.0.2
    firebase_core: ^3.1.1
    flutter:
        sdk: flutter
    gap: ^3.0.1
    popover: ^0.3.0
    number_editing_controller: ^1.2.1
    firebase_storage: ^12.1.0
    file_picker: ^8.0.5
    image_network: ^2.5.6
    dio: ^5.4.3+1
    google_maps_flutter: ^2.7.0
    url_launcher: ^6.3.0
    logger: ^2.3.0
    http: ^1.2.1
    string_extensions: ^0.7.3
    carousel_slider: ^5.0.0
dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0
    material_design_icons_flutter: ^7.0.7296

flutter:
    uses-material-design: true
    assets:
        - assets/map/restaurant_pin.png
        - assets/photos/photo.jpg
        - assets/backgrounds/b1.webp
        - assets/backgrounds/paper.webp
        - assets/backgrounds/burger.webp
        - assets/backgrounds/fota1.jpg
        - assets/backgrounds/bg2.jpg
