name: studfood
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.3 <4.0.0"

dependencies:
    cloud_firestore: ^4.17.0
    firebase_core: ^2.30.0
    flutter:
        sdk: flutter
    gap: ^3.0.1
    popover: ^0.3.0
    number_editing_controller: ^1.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    material_design_icons_flutter: ^7.0.7296

flutter:
    uses-material-design: true
