// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCaEbDWDP6OP00twHbwRTk9ErvqHT_38',
    appId: '1:13246258140:web:61b4b3d6ce5238d92a0d19',
    messagingSenderId: '13246258140',
    projectId: 'studfood-c8e12',
    authDomain: 'studfood-c8e12.firebaseapp.com',
    storageBucket: 'studfood-c8e12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN_DztgYzy6dTKjebgguCMaUi-rJ2se5k',
    appId: '1:13246258140:android:2cfd7a411e5a7e922a0d19',
    messagingSenderId: '13246258140',
    projectId: 'studfood-c8e12',
    storageBucket: 'studfood-c8e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1l11LkvI4h2TChCzdYVydcX9seWow3sU',
    appId: '1:13246258140:ios:d3959e7a5d1070102a0d19',
    messagingSenderId: '13246258140',
    projectId: 'studfood-c8e12',
    storageBucket: 'studfood-c8e12.appspot.com',
    iosBundleId: 'com.example.studfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1l11LkvI4h2TChCzdYVydcX9seWow3sU',
    appId: '1:13246258140:ios:d3959e7a5d1070102a0d19',
    messagingSenderId: '13246258140',
    projectId: 'studfood-c8e12',
    storageBucket: 'studfood-c8e12.appspot.com',
    iosBundleId: 'com.example.studfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpCaEbDWDP6OP00twHbwRTk9ErvqHT_38',
    appId: '1:13246258140:web:d28af0d0bce823732a0d19',
    messagingSenderId: '13246258140',
    projectId: 'studfood-c8e12',
    authDomain: 'studfood-c8e12.firebaseapp.com',
    storageBucket: 'studfood-c8e12.appspot.com',
  );
}
